### ISSUE TITLE
Database error show

### ISSUE THREAD

**Issue by ravirathoreds** [Rakeshvishnoi029/NodeJs-ExpressJs-mysql-Admin-panel#2]
where i can find the database file . i have created the database in the localhost but getting this error.
![image](https://user-images.githubusercontent.com/55428204/71973931-38282800-3236-11ea-8e01-ca67b32f78df.png)
Please help me solve this issue.
Thank you.

**Comment by gauravintellivision** [comment]
kindly change like this   subscription_id : { type: type.INTEGER },  in MembershipTransactions.js it will resolve coz forign key data type is different from primary key

**Comment by gauravintellivision** [comment]
but i have an issue after db installation i m not able to open over web i get only one thing after many changes Cannot GET /api/admin

**Comment by rananaresh86** [comment]
Can you let let me know how to starts this app? After create a database 'construction_app_admin' Do we need to create database tables?

I am getting following error after running "node app.js" :
localhost/tempprojects/NodeJs-Admin-Panel                                                                                                                                 ⍉
▶ node app.js
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/private/var/www/localhost/tempprojects/NodeJs-Admin-Panel/node_modules/bcrypt/lib/binding/bcrypt_lib.node, 1): no suitable image found.  Did find:
	/private/var/www/localhost/tempprojects/NodeJs-Admin-Panel/node_modules/bcrypt/lib/binding/bcrypt_lib.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
	/private/var/www/localhost/tempprojects/NodeJs-Admin-Panel/node_modules/bcrypt/lib/binding/bcrypt_lib.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/var/www/localhost/tempprojects/NodeJs-Admin-Panel/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/var/www/localhost/tempprojects/NodeJs-Admin-Panel/controllers/admin/UsersController.js:6:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by rananaresh86** [comment]
Hi @gauravintellivision ,

Did you get this working on your local machine?
I am getting this 'Cannot GET /' when browsing at: http://localhost:8082/

Thanks

**Comment by cookiesikeri** [comment]
> Can you let let me know how to starts this app? After create a database 'construction_app_admin' Do we need to create database tables?
> 
> I am getting following error after running "node app.js" :
> localhost/tempprojects/NodeJs-Admin-Panel ⍉
> ▶ node app.js
> module.js:681
> return process.dlopen(module, path._makeLong(filename));
> ^
> 
> Error: dlopen(/private/var/www/localhost/tempprojects/NodeJs-Admin-Panel/node_modules/bcrypt/lib/binding/bcrypt_lib.node, 1): no suitable image found. Did find:
> /private/var/www/localhost/tempprojects/NodeJs-Admin-Panel/node_modules/bcrypt/lib/binding/bcrypt_lib.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
> /private/var/www/localhost/tempprojects/NodeJs-Admin-Panel/node_modules/bcrypt/lib/binding/bcrypt_lib.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
> at Object.Module._extensions..node (module.js:681:18)
> at Module.load (module.js:565:32)
> at tryModuleLoad (module.js:505:12)
> at Function.Module._load (module.js:497:3)
> at Module.require (module.js:596:17)
> at require (internal/module.js:11:18)
> at Object. (/private/var/www/localhost/tempprojects/NodeJs-Admin-Panel/node_modules/bcrypt/bcrypt.js:6:16)
> at Module._compile (module.js:652:30)
> at Object.Module._extensions..js (module.js:663:10)
> at Module.load (module.js:565:32)
> at tryModuleLoad (module.js:505:12)
> at Function.Module._load (module.js:497:3)
> at Module.require (module.js:596:17)
> at require (internal/module.js:11:18)
> at Object. (/private/var/www/localhost/tempprojects/NodeJs-Admin-Panel/controllers/admin/UsersController.js:6:16)
> at Module._compile (module.js:652:30)
> at Object.Module._extensions..js (module.js:663:10)
> at Module.load (module.js:565:32)
> at tryModuleLoad (module.js:505:12)
> at Function.Module._load (module.js:497:3)
> at Module.require (module.js:596:17)
> at require (internal/module.js:11:18)

ypou are to create a databse name "construction_app_admin" and run "sequelize db:migrate"

**Comment by cookiesikeri** [comment]
create a database construction_app_admin and run sequelize db:migrate to run a full migration

**Comment by Shahiabood** [comment]
for me also it is showing Cannot GET /
what should i do to load the project

**Comment by pragneshpj** [comment]
any solution?
